# Generated by Django 5.2.2 on 2025-06-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
